/**
 * @author      : rbrugo (brugo.riccardo@gmail.com)
 * @created     : Friday Jan 02, 2026 21:56:39 CET
 * @description : implementations of partially-applicable arithmetic functions
 * @license     :
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 * */

#ifndef CB_LOGICAL_HPP
#define CB_LOGICAL_HPP

#include "detail/partial.hpp"
#include "detail/_config_begin.hpp"

namespace callables
{


// ....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo.... //
// ....................................AND..................................... //
// ....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo.... //
struct and_fn : public binary_fn<and_fn>, applicable_on_tuples<and_fn>
{
    template <typename T, typename U>
        requires requires(T && t, U && u) { CB_FWD(t) and CB_FWD(u); }
    constexpr CB_STATIC
    auto operator()(T && t, U && u) CB_CONST noexcept(noexcept(CB_FWD(t) and CB_FWD(u)))
        -> decltype(auto)
    { return CB_FWD(t) and CB_FWD(u); }

    using binary_fn<and_fn>::operator();
};

constexpr inline and_fn and_;

// ....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo.... //
// .....................................OR..................................... //
// ....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo.... //
struct or_fn : public binary_fn<or_fn>, applicable_on_tuples<or_fn>
{
    template <typename T, typename U>
        requires requires(T && t, U && u) { CB_FWD(t) or CB_FWD(u); }
    constexpr CB_STATIC
    auto operator()(T && t, U && u) CB_CONST noexcept(noexcept(CB_FWD(t) or CB_FWD(u)))
        -> decltype(auto)
    { return CB_FWD(t) or CB_FWD(u); }

    using binary_fn<or_fn>::operator();
};

constexpr inline or_fn or_;

// ....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo.... //
// .....................................XOR.................................... //
// ....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo.... //
struct xor_fn : public binary_fn<xor_fn>, applicable_on_tuples<xor_fn>
{
    template <typename T, typename U>
        requires requires(T && t, U && u) { CB_FWD(t) xor CB_FWD(u); }
    constexpr CB_STATIC
    auto operator()(T && t, U && u) CB_CONST noexcept(noexcept(CB_FWD(t) xor CB_FWD(u)))
        -> decltype(auto)
    { return CB_FWD(t) xor CB_FWD(u); }

    using binary_fn<xor_fn>::operator();
};

constexpr inline xor_fn xor_;

// ....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo.... //
// ....................................NOT..................................... //
// ....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo.... //
struct not_fn
{
    template <typename T>
        requires requires(T && t) { not CB_FWD(t); }
    constexpr CB_STATIC auto operator()(T && t) CB_CONST noexcept(noexcept( not CB_FWD(t) ))
    { return not CB_FWD(t); }
};

constexpr inline not_fn not_;

} // namespace callables

#endif /* CB_LOGICAL_HPP */
